{% set name = "conda-recipe-manager" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script: pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - conda-recipe-manager = conda_recipe_manager.commands.conda_recipe_manager:conda_recipe_manager
    - crm = conda_recipe_manager.commands.conda_recipe_manager:conda_recipe_manager

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.11
    # Version 8.2.0 introduces breaking changes around the `CliRunner` class, which breaks our
    # automated tests. We can allow for this version when it becomes available on `defaults`.
    - click >=8.1.7,<8.2.0
    - conda
    - jinja2
    - pyyaml
    - jsonschema
    - requests
    - gitpython
    - networkx
    - matplotlib-base
    - pygraphviz

test:
  imports:
    - conda_recipe_manager
  source_files:
    - .pytest.ini
    - tests/
  requires:
    - pip
    - pytest
    - pytest-xdist
    - pytest-socket
    - pyfakefs >=5.9.0
  commands:
    - pip check
    - python -m pytest -n auto --ignore=tests/test_aux_files tests/

about:
  home: https://github.com/conda/conda-recipe-manager
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Helper tool for recipes on aggregate.
  description: |
    Renders local recipes, provides build orders, find outdated recipes.
  doc_url: https://conda.github.io/conda-recipe-manager/index.html
  dev_url: https://github.com/conda/conda-recipe-manager
