# Apply to all files without committing:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
exclude: |
  (?x)^(
    .*/versioneer\.py|.*/_version\.py|.*/.*\.svg|tests/test_aux_files/.*|recipe/meta.yaml
  )$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
    exclude_types: ["json", "yaml", "pdf", "html", "png"]
  - id: check-ast
  - id: fix-byte-order-marker
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.1
  hooks:
  - id: check-github-actions
  - id: check-github-workflows
  - id: check-renovate
# `pre-commit` no longer provides a hook for `pytest`, by design
- repo: local
  hooks:
  # To prevent version inconsistencies between pre-commit and our `make` directives, we now invoke the `make`
  # versions of formatting and linting commands.
  - id: code-format
    language: system
    name: code-format
    pass_filenames: false
    entry: make format
  - id: pylint
    language: system
    name: pylint
    pass_filenames: false
    entry: make lint
  - id: mypy
    language: system
    name: mypy
    pass_filenames: false
    entry: make analyze
  - id: pytest-cov
    language: system
    name: pytest-cov
    always_run: true
    pass_filenames: false
    entry: make test-cov
    verbose: true
