name: conda-recipe-manager
channels:
  - defaults

dependencies:
  - black
  - isort
  - make
  - mypy
  # This is a temporary workaround for a new test failure. See Issue #369 for more details.
  # We allow for some 3.12 versions so the pre-commit 3.12 test can pass.
  - python >=3.11.11,!=3.11.13,<=3.12.9
  - pytest
  - pytest-cov
  - pytest-socket
  - pytest-xdist
  - pyfakefs
  # Match version with .pre-commit-config.yaml to ensure consistent rules with `make lint`.
  - pylint ==3.2.7
  - pip
  - click >=8.1.7
  - conda
  - jinja2
  - pyyaml
  - types-pyyaml
  - conda-build
  - jsonschema
  - types-jsonschema
  - requests
  - types-requests
  - gitpython
  - networkx
  - matplotlib-base
  - pygraphviz
  - pre-commit
  - sphinx
  - sphinx-rtd-theme
