name: conda-recipe-manager
channels:
  - defaults

dependencies:
  - black
  - isort
  - make
  - mypy
  - python >=3.11
  - pytest
  - pytest-cov
  - pytest-socket >=0.7.0
  - pytest-xdist
  - pyfakefs >=6.0.0
  # Match version with .pre-commit-config.yaml to ensure consistent rules with `make lint`.
  - pylint ==4.0.4
  - pip
  - click 8.2.1
  - conda
  - evalidate >=2.0.3,<3.0.0
  - jinja2
  - pyyaml
  - types-pyyaml
  - jsonschema
  - types-jsonschema
  - requests
  - types-requests
  - gitpython
  - networkx
  - matplotlib-base
  - pygraphviz
  - pre-commit
  # Documentation generation packages
  # NOTE: `sphinx` 9.1.0 is not available for Python 3.11, which is the minimum supported by CRM.
  - sphinx ==8.2.3
  # NOTE: 3.14 does not support Python 3.14 yet.
  - sphinx-book-theme >=1.1.4
