name: Set up environment
description: Set up a conda-recipe-manager environment

inputs:
  python-version:
    description: "Version of python to use in the conda environment."
    required: false
    default: "3.11"

runs:
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ inputs.python-version }}
        activate-environment: conda-recipe-manager
        environment-file: environment.yaml
    - name: Create Environment
      shell: bash
      run: |
        source $CONDA/bin/activate
        conda activate conda-recipe-manager
        pip install .
